"""booking status flow

Revision ID: 6aa42b67fa77
Revises: 9720e4706ea2
Create Date: 2025-12-22 10:34:53.243632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6aa42b67fa77'
down_revision: Union[str, None] = '9720e4706ea2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_availability_templates_day_of_week', table_name='availability_templates')
    op.drop_index('ix_availability_templates_lawyer_id', table_name='availability_templates')
    op.drop_table('availability_templates')
    op.drop_index('ix_token_queue_client_id', table_name='token_queue')
    op.drop_index('ix_token_queue_date', table_name='token_queue')
    op.drop_index('ix_token_queue_lawyer_id', table_name='token_queue')
    op.drop_table('token_queue')
    op.drop_index('ix_disputes_id', table_name='disputes')
    op.drop_table('disputes')
    op.drop_index('ix_blackout_days_date', table_name='blackout_days')
    op.drop_index('ix_blackout_days_lawyer_id', table_name='blackout_days')
    op.drop_table('blackout_days')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blackout_days',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('lawyer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['lawyer_id'], ['users.id'], name='blackout_days_lawyer_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='blackout_days_pkey'),
    sa.UniqueConstraint('lawyer_id', 'date', name='uq_blackout_days_lawyer_date', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index('ix_blackout_days_lawyer_id', 'blackout_days', ['lawyer_id'], unique=False)
    op.create_index('ix_blackout_days_date', 'blackout_days', ['date'], unique=False)
    op.create_table('disputes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'PENDING'::character varying"), autoincrement=False, nullable=False),
    sa.Column('admin_note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name='disputes_booking_id_fkey'),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], name='disputes_client_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='disputes_pkey')
    )
    op.create_index('ix_disputes_id', 'disputes', ['id'], unique=False)
    op.create_table('token_queue',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('token_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('lawyer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('waiting', 'served', name='token_queue_status'), autoincrement=False, nullable=False),
    sa.Column('served_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], name='token_queue_client_id_fkey'),
    sa.ForeignKeyConstraint(['lawyer_id'], ['users.id'], name='token_queue_lawyer_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='token_queue_pkey'),
    sa.UniqueConstraint('lawyer_id', 'date', 'token_number', name='uq_token_queue_lawyer_date_token_number', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index('ix_token_queue_lawyer_id', 'token_queue', ['lawyer_id'], unique=False)
    op.create_index('ix_token_queue_date', 'token_queue', ['date'], unique=False)
    op.create_index('ix_token_queue_client_id', 'token_queue', ['client_id'], unique=False)
    op.create_table('availability_templates',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('lawyer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('day_of_week', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('slot_minutes', sa.INTEGER(), server_default=sa.text('30'), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['lawyer_id'], ['users.id'], name='availability_templates_lawyer_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='availability_templates_pkey')
    )
    op.create_index('ix_availability_templates_lawyer_id', 'availability_templates', ['lawyer_id'], unique=False)
    op.create_index('ix_availability_templates_day_of_week', 'availability_templates', ['day_of_week'], unique=False)
    # ### end Alembic commands ###
















