"""update booking statuses

Revision ID: b0d38fe95f95
Revises: 6329ae97b2e9
Create Date: 2025-12-22 01:03:42.930498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b0d38fe95f95'
down_revision: Union[str, None] = '6329ae97b2e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_disputes_id', table_name='disputes')
    op.drop_table('disputes')
    op.create_index(op.f('ix_bookings_id'), 'bookings', ['id'], unique=False)
    op.add_column('kyc_submissions', sa.Column('full_name', sa.String(), nullable=False))
    op.add_column('kyc_submissions', sa.Column('bar_council_id', sa.String(), nullable=False))
    op.add_column('kyc_submissions', sa.Column('address', sa.String(), nullable=False))
    op.add_column('kyc_submissions', sa.Column('contact_number', sa.String(), nullable=False))
    op.add_column('kyc_submissions', sa.Column('bar_certificate_url', sa.String(), nullable=True))
    op.drop_column('kyc_submissions', 'nic_front_url')
    op.drop_column('kyc_submissions', 'nic_back_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kyc_submissions', sa.Column('nic_back_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('kyc_submissions', sa.Column('nic_front_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('kyc_submissions', 'bar_certificate_url')
    op.drop_column('kyc_submissions', 'contact_number')
    op.drop_column('kyc_submissions', 'address')
    op.drop_column('kyc_submissions', 'bar_council_id')
    op.drop_column('kyc_submissions', 'full_name')
    op.drop_index(op.f('ix_bookings_id'), table_name='bookings')
    op.create_table('disputes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'PENDING'::character varying"), autoincrement=False, nullable=False),
    sa.Column('admin_note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name='disputes_booking_id_fkey'),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], name='disputes_client_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='disputes_pkey')
    )
    op.create_index('ix_disputes_id', 'disputes', ['id'], unique=False)
    # ### end Alembic commands ###
















