"""add lawyer_profiles

Revision ID: cc9b4907806e
Revises: 5b8e5f8e97e3
Create Date: 2025-12-27 19:27:10.792132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cc9b4907806e'
down_revision: Union[str, None] = '5b8e5f8e97e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('availability_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lawyer_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('slot_minutes', sa.Integer(), server_default=sa.text('30'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lawyer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_availability_templates_day_of_week'), 'availability_templates', ['day_of_week'], unique=False)
    op.create_index(op.f('ix_availability_templates_lawyer_id'), 'availability_templates', ['lawyer_id'], unique=False)
    op.create_table('blackout_days',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lawyer_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['lawyer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lawyer_id', 'date', name='uq_blackout_days_lawyer_date')
    )
    op.create_index(op.f('ix_blackout_days_date'), 'blackout_days', ['date'], unique=False)
    op.create_index(op.f('ix_blackout_days_lawyer_id'), 'blackout_days', ['lawyer_id'], unique=False)
    op.create_table('lawyer_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('specialization', sa.String(length=255), nullable=True),
    sa.Column('languages', sa.JSON(), nullable=True),
    sa.Column('years_of_experience', sa.Integer(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('rating', sa.Float(), server_default='0', nullable=True),
    sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lawyer_profiles_id'), 'lawyer_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_lawyer_profiles_user_id'), 'lawyer_profiles', ['user_id'], unique=True)
    
    op.execute("ALTER TABLE disputes DROP CONSTRAINT IF EXISTS disputes_client_id_fkey")
    op.execute("ALTER TABLE disputes DROP CONSTRAINT IF EXISTS disputes_booking_id_fkey")
    op.create_foreign_key(None, 'disputes', 'bookings', ['booking_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'disputes', 'users', ['client_id'], ['id'], ondelete='CASCADE')
    op.execute("CREATE INDEX IF NOT EXISTS ix_documents_id ON documents (id)")
    op.alter_column('intake_forms', 'case_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('intake_forms', 'subject',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('intake_forms', 'details',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('intake_forms', 'urgency',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('intake_forms', 'answers_json',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.create_index(op.f('ix_intake_forms_id'), 'intake_forms', ['id'], unique=False)
    op.alter_column('kyc_submissions', 'lawyer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('kyc_submissions', 'lawyer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_intake_forms_id'), table_name='intake_forms')
    op.alter_column('intake_forms', 'answers_json',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('intake_forms', 'urgency',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('intake_forms', 'details',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('intake_forms', 'subject',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('intake_forms', 'case_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_constraint(None, 'disputes', type_='foreignkey')
    op.drop_constraint(None, 'disputes', type_='foreignkey')
    op.create_foreign_key('disputes_booking_id_fkey', 'disputes', 'bookings', ['booking_id'], ['id'])
    op.create_foreign_key('disputes_client_id_fkey', 'disputes', 'users', ['client_id'], ['id'])
    op.create_table('checklist_templates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lawyer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('helper_text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('required', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['lawyer_id'], ['lawyers.id'], name='checklist_templates_lawyer_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='checklist_templates_pkey')
    )
    op.create_index('ix_checklist_templates_id', 'checklist_templates', ['id'], unique=False)
    op.create_table('service_packages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lawyer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['lawyer_id'], ['lawyers.id'], name='service_packages_lawyer_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='service_packages_pkey')
    )
    op.create_index('ix_service_packages_id', 'service_packages', ['id'], unique=False)
    op.drop_index(op.f('ix_lawyer_profiles_user_id'), table_name='lawyer_profiles')
    op.drop_index(op.f('ix_lawyer_profiles_id'), table_name='lawyer_profiles')
    op.drop_table('lawyer_profiles')
    op.drop_index(op.f('ix_blackout_days_lawyer_id'), table_name='blackout_days')
    op.drop_index(op.f('ix_blackout_days_date'), table_name='blackout_days')
    op.drop_table('blackout_days')
    op.drop_index(op.f('ix_availability_templates_lawyer_id'), table_name='availability_templates')
    op.drop_index(op.f('ix_availability_templates_day_of_week'), table_name='availability_templates')
    op.drop_table('availability_templates')
    # ### end Alembic commands ###

















